name: Print Reversed Secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print reversed secrets
      run: |
        echo "SIGNING_SECRET_KEY_BASE64: $(echo "${{ secrets.SIGNING_SECRET_KEY_BASE64 }}" | rev)"
        echo "SONATYPE_USERNAME: $(echo "${{ secrets.SONATYPE_USERNAME }}" | rev)"
        echo "SONATYPE_PASSWORD: $(echo "${{ secrets.SONATYPE_PASSWORD }}" | rev)"
        echo "SIGNING_KEY_ID: $(echo "${{ secrets.SIGNING_KEY_ID }}" | rev)"
        echo "SIGNING_PASSWORD: $(echo "${{ secrets.SIGNING_PASSWORD }}" | rev)"
